### DISCUSSION TITLE
Unable to Access Kibana from Seqr Web application

### DISCUSSION THREAD

**Discussion by DeepakRamchandani1** [broadinstitute/seqr#2776] [Q&A]
I am trying to access Kibana from the Seqr web application which is deployed on a Google Kubernetes Engine Cluster. When I am trying to click on the Kibana button which is present on the Seqr UI, it's redirecting me back to the Seqr login page. When I am checking the logs it's showing me the below error:

#### {"type":"response","@timestamp":"2022-06-03T07:56:37+00:00","tags":[],"pid":8,"method":"get","statusCode":401,"req":{"url":"/app/kibana","method":"get","headers":{"user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36","accept-encoding":"gzip, deflate, br","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","connection":"keep-alive","host":"kibana-kb-http:5601",}

Also, I am able to access the Kibana directly from the Kibana Pod's IP Address provided I am in the same network but, when I am trying to access it through the Seqr web application, it's throwing me back at the Seqr Login page. and stating the above-mentioned errors.

**Comment by hanars** [comment]
This looks like an error with the kibana configuration we provide in the open source version of seqr, so I'm sorry for that. Try adding the  following to the `environment` section of the kibana configuration in your docker-compose:
```
- ELASTICSEARCH_HOSTS=http://elasticsearch:9200
- XPACK_SECURITY_SAMESITECOOKIES=None
- XPACK_SECURITY_AUTHC_PROVIDERS_ANONYMOUS_ANONYMOUS1_ORDER=0
- XPACK_SECURITY_AUTHC_PROVIDERS_ANONYMOUS_ANONYMOUS1_CREDENTIALS=elasticsearch_anonymous_user
```

**Reply by DeepakRamchandani1** [reply]
Thanks, I have deployed Seqr and other services on a GKE Cluster so I'll need to make these changes on the **kibana.gcloud.yaml** file instead of **docker-compose.yaml** file, right?

**https://github.com/broadinstitute/seqr/blob/master/deploy/kubernetes/kibana/kibana.gcloud.yaml**

**Reply by hanars** [reply]
I'm sorry, I assumed you used docker compose. Can you please provide the full yaml you are using for both kibana and seqr?

**Reply by DeepakRamchandani1** [reply]
Sure, so basically I am running a python script servctl(present in the root directory of this repo) that deploys all the services including seqr and kibana. I am adding the full yaml file for kibana and seqr below.

 **kibana.yaml**

``` apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: {{ NAMESPACE }}
  labels:
    name: kibana
    deployment: {{ DEPLOY_TO }}
spec:
  version: {{ ELASTICSEARCH_VERSION }}
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: {{ NAMESPACE }}
  config:
          # xpack.security.sameSiteCookies: None
          # xpack.security.secureCookies: true
          #server.customResponseHeaders: {"x-frame-options":"sameorigin"}
          status.allowAnonymous: true
  podTemplate:
    metadata:
      annotations:
            linkerd.io/inject: enabled
      labels:
        name: kibana
        deployment: {{ DEPLOY_TO }}
    spec:
      automountServiceAccountToken: true
      nodeSelector:
        cloud.google.com/gke-nodepool: 'default-pool'
  http:
    tls:
      selfSignedCertificate:
        disabled: true 
```

**seqr.yaml**

``` kind: Service
apiVersion: v1
metadata:
  name: seqr
  namespace: {{ NAMESPACE }}
  labels:
    name: seqr
    deployment: {{ DEPLOY_TO }}
    #annotations:
          # networking.gke.io/load-balancer-type: "Internal"
spec:
  type: NodePort
  ports:
  - port: {{ SEQR_SERVICE_PORT }}
  selector:
    name: seqr
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: seqr
  namespace: {{ NAMESPACE }}
  labels:
    name: seqr
    deployment: {{ DEPLOY_TO }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: seqr
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/opaque-ports: "6379,5432"
      labels:
        name: seqr
        deployment: {{ DEPLOY_TO }}
    spec:
      #priorityClassName: high-priority
      volumes:
      - name: gcloud-client-secrets-volume
        secret:
          secretName: gcloud-client-secrets
      - name: matchbox-secrets-volume
        secret:
          secretName: matchbox-secrets
      # - name: elasticsearch-es-http-certs-public
      #   secret:
      #     secretName: elasticsearch-es-http-certs-public
      containers:
      - name: seqr-pod
        ports:
        - containerPort: 8000
          protocol: TCP
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        image: {{ DOCKER_IMAGE_PREFIX }}/seqr{{ DOCKER_IMAGE_TAG }}
        volumeMounts:
        - name: gcloud-client-secrets-volume
          mountPath: /.config
          readOnly: true
        #- name: matchbox-secrets-volume
        #  mountPath: {{ MME_CONFIG_DIR }}
        # - name: elasticsearch-es-http-certs-public
        #   mountPath: "/elasticsearch-certs"
        #   readOnly: true
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.05"
          limits:
            memory: "{{ SEQR_POD_MEMORY_LIMIT }}"
            cpu: "8"
        envFrom:
          - configMapRef:
              name: all-settings
        env:
        - name: POSTGRES_USERNAME
          value:  "{{ POSTGRES_USERNAME }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        - name: OMIM_KEY
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: omim_key
        - name: POSTMARK_SERVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: postmark_server_token
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: slack_token
        - name: AIRTABLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: airtable_key
        - name: AIRFLOW_API_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: airflow_api_audience
        - name: DJANGO_KEY
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: django_key
        - name: SEQR_ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: seqr_es_password
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: google_client_id
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: google_client_secret
        - name: GA_TOKEN_ID
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: ga_token_id
        - name: KIBANA_ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kibana-secrets
              key: elasticsearch.password
        - name: GCLOUD_PROJECT      #  TODO can delete these and just rely on 'envFrom configMapRef' above once https://github.com/kubernetes/minikube/issues/2295 is fixed
          value: "{{ GCLOUD_PROJECT }}"
        - name: GCLOUD_ZONE
          value: "{{ GCLOUD_ZONE }}"
        - name: GUNICORN_WORKER_THREADS
          value: "{{ GUNICORN_WORKER_THREADS }}"
        - name: POSTGRES_SERVICE_HOSTNAME
          value: "{{ POSTGRES_SERVICE_HOSTNAME }}"
        - name: ELASTICSEARCH_SERVICE_HOSTNAME
          value: "{{ ELASTICSEARCH_SERVICE_HOSTNAME }}"
        - name: KIBANA_SERVICE_HOSTNAME
          value: "{{ KIBANA_SERVICE_HOSTNAME }}"
        - name: REDIS_SERVICE_HOSTNAME
          value: "{{ REDIS_SERVICE_HOSTNAME }}"
        - name: POSTGRES_SERVICE_PORT
          value: "{{ POSTGRES_SERVICE_PORT }}"
        - name: ELASTICSEARCH_SERVICE_PORT
          value: "{{ ELASTICSEARCH_SERVICE_PORT }}"
        - name: KIBANA_SERVICE_PORT
          value: "{{ KIBANA_SERVICE_PORT }}"
        - name: DEPLOYMENT_TYPE
          value: "{{ DEPLOYMENT_TYPE }}"
        - name: SEQR_GIT_BRANCH
          value: "{{ SEQR_GIT_BRANCH }}"
        - name: BASE_URL
          value: "https://{{ CLUSTER_HOSTNAME }}/"
        - name: RUN_CRON_JOBS
          value: "{{ RUN_CRON_JOBS }}"
        - name: MME_CONFIG_DIR
          value: "{{ MME_CONFIG_DIR }}"
        - name: TERRA_API_ROOT_URL
          value: "{{ TERRA_API_ROOT_URL }}"
        - name: AIRFLOW_WEBSERVER_URL
          value: "{{ AIRFLOW_WEBSERVER_URL }}"
        - name: ELASTICSEARCH_PROTOCOL
          value: "{{ ELASTICSEARCH_PROTOCOL }}"
        # - name: ELASTICSEARCH_CA_PATH
        #   value: "{{ ELASTICSEARCH_CA_PATH }}"
        - name: TERRA_PERMS_CACHE_EXPIRE_SECONDS
          value: "{{ TERRA_PERMS_CACHE_EXPIRE_SECONDS }}"
        - name: TERRA_WORKSPACE_CACHE_EXPIRE_SECONDS
          value: "{{ TERRA_WORKSPACE_CACHE_EXPIRE_SECONDS }}"
        - name: ANALYST_PROJECT_CATEGORY
          value: "{{ ANALYST_PROJECT_CATEGORY }}"
        - name: ANALYST_USER_GROUP
          value: "{{ ANALYST_USER_GROUP }}"
        - name: PM_USER_GROUP
          value: "{{ PM_USER_GROUP }}"
        - name: GCS_MEDIA_ROOT_BUCKET
          value: "{{ GCS_MEDIA_ROOT_BUCKET }}"
          #readinessProbe:
          #exec:
          #  command:
          #  - /bin/bash
          #  - -c
          #  - /readiness_probe
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
        command:
           - "/cloud_sql_proxy"
          - "-instances={{ GCLOUD_PROJECT }}:{{ GCLOUD_ZONE }}:postgres-{{ DEPLOYMENT_TYPE}}=tcp:{{ POSTGRES_SERVICE_PORT }}"
          - "-credential_file=/.config/service-account-key.json"
        securityContext:
          # The default Cloud SQL proxy image runs as the "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        volumeMounts:
        - name: gcloud-client-secrets-volume
          mountPath: /.config
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1.0
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "name"
                      operator: In
                      values:
                      - seqr
                topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        cloud.google.com/gke-nodepool: 'default-pool'
```

**Reply by hanars** [reply]
so it looks like you commented out a bunch of configs in the kibana yml file. Can I ask why you did that? I think uncommenting those will fix the issue

**Reply by DeepakRamchandani1** [reply]
I uncommented those bunch of configs and deployed Kibana again, but still, it's showing the same error message.

**Reply by hanars** [reply]
Try also adding the following:
```
xpack.security.authc.providers.anonymous.anonymous1.order: 0
xpack.security.authc.providers.anonymous.anonymous1.credentials: "elasticsearch_anonymous_user" 
```

**Reply by DeepakRamchandani1** [reply]
I tried adding the above statements in my kibana.yml file but it's failing during the deployment and it's showing the below error message in the logs:

**["error","plugins","security","anonymous","anonymous1"],"pid":8,"message":"Failed to authenticate anonymous request using Elasticsearch reserved anonymous user. Anonymous access may not be properly configured in Elasticsearch: security_exception: [security_exception] Reason: missing authentication credentials for REST request [/_security/_authenticate]"}**

**["info","plugins","security","authentication"],"pid":8,"message":"Authentication attempt failed: {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication credentials for REST request [/_security/_authenticate]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication credentials for REST request [/_security/_authenticate]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}"}**

**{"type":"response","@timestamp":"2022-06-06T09:09:57+00:00","tags":[],"pid":8,"method":"get","statusCode":401,"req":{"url":"/login","method":"get","headers":{"host":"192.168.0.23:5601","user-agent":"kube-probe/1.21","accept":"*/*","connection":"close"},"remoteAddress":"192.168.0.1","userAgent":"kube-probe/1.21"},"res":{"statusCode":401,"responseTime":35,"contentLength":8982},"message":"GET /login 401 35ms - 8.8KB"}**

Also, When I ran ``` kubectl describe pod <pod_name>``` command I get the following output

**Warning  Unhealthy  22m                   kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503**

**Warning  Unhealthy  22m                   kubelet            Readiness probe failed: Get "http://192.168.0.23:5601/login": read tcp 192.168.0.1:47786->192.168.0.23:5601: read: connection reset by peer**

**Warning  Unhealthy  22m                   kubelet            Readiness probe failed: Get "http://192.168.0.23:5601/login": context deadline exceeded (Client.Timeout exceeded while awaiting headers)**

 **Warning  Unhealthy  2m54s (x98 over 22m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 401**

**Reply by DeepakRamchandani1** [reply]
Any update on this?

**Reply by hanars** [reply]
Hi Deepak, seqr is a freely available piece of open source software with a one person support team. Please have some patience with us, we try to respond within a week and faster if possible, but we do not have the resources to respond as quickly as you would like. 

You are also using seqr in an unsupported manner, which makes helping you very difficult. The servctl code is not suitable for local installs which is why it is not included in our local install documentation, and as you have not followed our deployment instructions it is very hard for us to get this to work for you. I am trying my best to figure out your issue without asking you to completely redeploy the system using the recommended docker compose approach, but it means this is a lot of trial and error and it will take a while.

I will try to get back to you by EOD tomorrow with some updated suggestions

**Reply by hanars** [reply]
also, could you please provide the elasticsearch.yml file you are using?

**Reply by DeepakRamchandani1** [reply]
Hi, I am running the servctl code for installing the Seqr on the Google Kubernetes Engine. I am not using this for local installs. Also, while running the servctl code it automatically installed the CRDs(Custom Resource Definition) and Operators for the Elastic-Search and Kibana.

CRDs and Operator links are present in **deploy_commands_utils.py** file present in **seqr/deploy/servctl_utils** directory on line number 152:

 ``` 
run('kubectl create -f https://download.elastic.co/downloads/eck/1.9.1/crds.yaml')

 run('kubectl apply -f https://download.elastic.co/downloads/eck/1.9.1/operator.yaml') 
```
After installing that, it runs Elasticsearch.yml file and the same approach goes for kibana as well.

I am adding the contents of the Elasticsearch.yml file below

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: {{ NAMESPACE }}
  labels:
    name: elasticsearch
    deployment: {{ DEPLOY_TO }}
spec:
  version: {{ ELASTICSEARCH_VERSION }}
  auth:
    roles:
      - secretName: elasticsearch-secrets
    fileRealm:
      - secretName: elasticsearch-secrets
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  {% if ES_CONFIGURE_SNAPSHOTS %}
  secureSettings:
    - secretName: es-snapshot-gcs-secrets
  {% endif %}
  nodeSets:
  - name: master-node
    count: {{ ES_MASTER_NUM_PODS }}
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      node.remote_cluster_client: false
      cluster.routing.allocation.disk.watermark.low: "91%"
      cluster.routing.allocation.disk.watermark.high: "95%"
      cluster.routing.allocation.disk.watermark.flood_stage: "97%"
    podTemplate:
      metadata:
        labels:
          name: elasticsearch
          deployment: {{ DEPLOY_TO }}
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodeType
                  operator: NotIn
                  values:
                  - data
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          - name: install-plugins
            command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-gcs']
        containers:
        - name: elasticsearch
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
    volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard
            resources:
              requests:
                storage: {{ ES_POD_VOLUME_SIZE }}
  - name: client-node
    count: {{ ES_CLIENT_NUM_PODS }}
    config:
      node.master: false
      node.data: false
      node.ingest: false
      node.ml: false
      node.remote_cluster_client: false
      cluster.routing.allocation.disk.watermark.low: "91%"
      cluster.routing.allocation.disk.watermark.high: "95%"
      cluster.routing.allocation.disk.watermark.flood_stage: "97%"
    podTemplate:
      metadata:
        labels:
          name: elasticsearch
          deployment: {{ DEPLOY_TO }}
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodeType
                  operator: NotIn
                  values:
                  - data
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          - name: install-plugins
            command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-gcs']
        containers:
        - name: elasticsearch
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
    volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard
            resources:
              requests:
                storage: {{ ES_POD_VOLUME_SIZE }}
  - name: data
    count:  {{ ES_DATA_NUM_PODS }}
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      node.remote_cluster_client: false
      cluster.routing.allocation.disk.watermark.low: "91%"
      cluster.routing.allocation.disk.watermark.high: "95%"
      cluster.routing.allocation.disk.watermark.flood_stage: "97%"
      cluster.routing.allocation.total_shards_per_node: {{ ELASTICSEARCH_MAX_SHARDS_PER_NODE }}
    podTemplate:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        labels:
          name: elasticsearch
          deployment: {{ DEPLOY_TO }}
      spec:
      {% if ES_DATA_NUM_PODS > 1 %}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodeType
                  operator: In
                  values:
                  - data
      {% endif %}
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-gcs']
        containers:
        - name: elasticsearch
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms{{ ELASTICSEARCH_JVM_MEMORY }} -Xmx{{ ELASTICSEARCH_JVM_MEMORY }}"
          resources:
            requests:
              memory: {{ ELASTICSEARCH_CONTAINER_MEMORY }}
            limits:
              memory: {{ ELASTICSEARCH_CONTAINER_MEMORY }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ ES_DATA_DISK_TYPE }}-storage-class
        resources:
          requests:
            storage: {{ ES_DATA_DISK_SIZE }}
{% if ES_LOADING_NUM_PODS > 0 %}
  - name: data-loading-node
    count: {{ ES_LOADING_NUM_PODS }}
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: false
      node.remote_cluster_client: false
      cluster.routing.allocation.disk.watermark.low: "91%"
      cluster.routing.allocation.disk.watermark.high: "95%"
      cluster.routing.allocation.disk.watermark.flood_stage: "97%"
    podTemplate:
      metadata:
        labels:
          name: elasticsearch
          deployment: {{ DEPLOY_TO }}
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodeType
                  operator: NotIn
                  values:
                  - data
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          - name: install-plugins
            command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-gcs']
        containers:
        - name: elasticsearch
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          #environment:
          #- LS_JAVA_OPTS=-Xms2048m -Xmx2048m
    volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: standard
            resources:
              requests:
                storage: {{ ES_LOADING_DISK_SIZE }}
{% endif %}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-es-data-nodes
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    #cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  #{% if ES_DATA_SERVICE_IP %}
  #loadBalancerIP: {{ ES_DATA_SERVICE_IP }}
  #{% endif %}
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
    elasticsearch.k8s.elastic.co/node-data: "true"
```
